In [34]:
import pandas as pd
import pickle

In [35]:
file = "./new_ru_clusters_v2.xlsx"
big_dataset = "../data/04-01_06-30sDate_80.xlsx"
df_tr = pd.read_pickle('./transformed_pickle.pkl')

In [36]:
df_tr

,clus0,clus1,clus2,clus3,clus4,clus5,clus6,clus7,clus8,clus9,clus10,clus11,clus12,clus13,clus14,clus15,clus16,clus17,clus18,clus19
0,1.021816,1.072850,1.279533,1.387559,1.032203,1.380312,1.384832,0.975785,1.285788,1.030716,1.262144,1.011147,0.998272,1.054176,1.024156,1.035649,1.066760,1.052430,1.073079,1.065592
1,1.019920,1.066228,1.279609,1.366732,1.023912,1.380312,1.362766,1.015242,1.285788,1.027129,1.262144,0.995653,0.999006,1.020951,1.006140,1.034362,1.057150,1.037852,1.075064,1.054566
2,1.013021,1.066665,1.204334,1.369795,1.021968,1.360126,1.366013,1.004825,1.285788,1.012806,1.262144,0.997121,0.993738,1.040456,1.006521,0.910314,1.051659,1.037188,1.068665,1.050866
3,1.007513,1.050546,1.240233,1.387559,1.011451,1.380312,1.384832,0.998203,1.285636,1.017782,1.262144,0.968797,0.990509,0.918338,0.994454,0.980878,1.022897,0.985670,1.060815,0.938210
4,1.023411,1.073342,1.276957,1.367240,1.033154,1.380312,1.363305,1.024950,1.285788,1.031068,1.262144,1.010468,0.999318,1.063505,1.023985,1.032681,1.068123,1.052386,1.026300,1.069464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6720,1.016711,1.066506,1.269600,1.387559,1.029226,1.380312,1.384832,1.022469,1.284995,1.030135,1.262144,0.997247,0.998402,1.054443,1.016903,1.026838,1.063913,1.034485,1.073249,1.065895
6721,0.961442,1.066114,1.263525,1.382528,1.025508,1.380312,1.379504,1.023043,1.279900,1.020762,1.260277,1.009627,0.995868,1.062737,1.018383,1.033751,1.064499,1.048447,1.047852,1.066842
6722,1.013388,1.067712,1.260868,1.383123,1.026601,1.377971,1.371201,1.016842,1.285594,1.018585,1.261695,1.007046,0.994287,1.056672,1.017114,1.026609,1.065089,1.047940,1.068162,1.065057
6723,1.018441,1.066657,1.261946,1.383413,1.026609,1.375604,1.373013,1.003343,1.285077,0.989085,1.262144,1.002329,0.995550,1.052390,1.015774,1.030309,1.057967,1.044657,1.068055,1.052872
6724,1.013330,1.063647,1.271255,1.384740,1.025304,1.373012,1.381903,1.015969,1.285629,1.023171,1.262144,0.999989,0.990327,1.054822,1.001790,1.026191,1.061660,1.041643,1.058117,1.064252

In [ ]:
df = pd.read_excel(file, dtype=str)
df.head()

In [38]:
df.shape

(6725, 7)

In [ ]:
df_tr = df_tr.join(df['Incident_Number'])
df_tr.head()

In [ ]:
cols = df_tr.columns.tolist()
cols = cols[-1:] + cols[:-1]
df_tr = df_tr[cols]
df_tr

In [41]:
df_big = pd.read_excel(big_dataset, dtype=str)

In [ ]:
df_big.head()

In [43]:

df_big.dropna(subset = ["incidenType"], inplace=True)

In [ ]:
df_big.head()

In [45]:
df_big.shape

(12900, 2)

In [46]:
df_with_inc = pd.merge(df_tr, df_big, on=['Incident_Number'])

In [47]:
df_with_inc.shape

(6725, 22)

In [ ]:
df_with_inc.tail()

In [49]:
df_with_inc.to_excel('new_distance_and_inctype_v2.xlsx', index=False)